### PR TITLE
Completed issue #20

### PR DESCRIPTION
**Pull request by Shpendiiiii**
Hi, 

Set up swagger, and modified the project structure to a standard NestJs one. Also completed issue #20. 

Please run ```yarn install``` and then ```ts-node seed.ts``` (this populates the db with test data), and then ```nest start```. Go to "localhost:3000/api", and test out the api.

To see the user_ids and type_ids (i.e. the test data), please run in the terminal ```prisma studio```. 

Please let me know if it is not working for you, or if you are not able to set it up. I will be there to help as soon as possible.

Shpendi

p.s. create your own .env file in order to connect to PGSQL instance.

### CODE REVIEW

**Comment by Mohmn** [comment]
u have  deleted the ```libs``` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii

**Comment by GuningShen** [comment]
Hi @Shpendiiiii , since we are following a monorepo architecture, could you move the dtos to shared library?

**Comment by Shpendiiiii** [comment]
> u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii

I found that structure cumbersome, and used a standard one instead. Additionally, the prisma folder was inside of that and inside the root, which is redundant. 

Also, there is no need to have a separate folder inside of a folder for DTOs as well. They can very well live within the folder of the services itself, or within /src itself. 

At the end of the day, it is more readable, and most importantly, it runs.

**Comment by Shpendiiiii** [comment]
> Hi @Shpendiiiii , since we are following a monorepo architecture, could you move the dtos to shared library?

In this pull request or the future ones?

**Comment by Mohmn** [comment]
> u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii



> > u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii
> 
> I found that structure cumbersome, and used a standard one instead. Additionally, the prisma folder was inside of that and inside the root, which is redundant.
> 
> Also, there is no need to have a separate folder inside of a folder for DTOs as well. They can very well live within the folder of the services itself, or within /src itself.
> 
> At the end of the day, it is more readable, and most importantly, it runs.

I agree that the DTO folder can be seen as redundant, but since we are following a monorepo pattern, we have added it to adjust our TypeScript configurations. In the future, there might be genuine cases where moving some code under the libs directory could be beneficial.

I also noticed that you removed the app folder and moved it into the src folder. This might break the monorepo pattern that we are trying to achieve. Regarding the location of the Prisma folder, I'm not entirely sure where it should be placed.

Could you please provide some insight on the best practices for organizing these folders while maintaining the monorepo structure?
@Shpendiiiii

**Comment by Shpendiiiii** [comment]
> > u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii
> 
> > > u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii
> > 
> > 
> > I found that structure cumbersome, and used a standard one instead. Additionally, the prisma folder was inside of that and inside the root, which is redundant.
> > Also, there is no need to have a separate folder inside of a folder for DTOs as well. They can very well live within the folder of the services itself, or within /src itself.
> > At the end of the day, it is more readable, and most importantly, it runs.
> 
> I agree that the DTO folder can be seen as redundant, but since we are following a monorepo pattern, we have added it to adjust our TypeScript configurations. In the future, there might be genuine cases where moving some code under the libs directory could be beneficial.
> 
> I also noticed that you removed the app folder and moved it into the src folder. This might break the monorepo pattern that we are trying to achieve. Regarding the location of the Prisma folder, I'm not entirely sure where it should be placed.
> 
> Could you please provide some insight on the best practices for organizing these folders while maintaining the monorepo structure? @Shpendiiiii

In that case, I will have to put that part that I worked into its own structure, and allow for other applications to exist. Should I go ahead? 

I didn't realize that there needed to be more apps inside this project, I thought the like system would be the only one.

**Comment by Mohmn** [comment]
> > > u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii
> > 
> > > > u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii
> > > 
> > > 
> > > I found that structure cumbersome, and used a standard one instead. Additionally, the prisma folder was inside of that and inside the root, which is redundant.
> > > Also, there is no need to have a separate folder inside of a folder for DTOs as well. They can very well live within the folder of the services itself, or within /src itself.
> > > At the end of the day, it is more readable, and most importantly, it runs.
> > 
> > I agree that the DTO folder can be seen as redundant, but since we are following a monorepo pattern, we have added it to adjust our TypeScript configurations. In the future, there might be genuine cases where moving some code under the libs directory could be beneficial.
> > 
> > I also noticed that you removed the app folder and moved it into the src folder. This might break the monorepo pattern that we are trying to achieve. Regarding the location of the Prisma folder, I'm not entirely sure where it should be placed.
> > 
> > Could you please provide some insight on the best practices for organizing these folders while maintaining the monorepo structure? @Shpendiiiii
> 
> In that case, I will have to put that part that I worked into its own structure, and allow for other applications to exist. Should I go ahead? 
> 
> I didn't realize that there needed to be more apps inside this project, I thought the like system would be the only one. 

Yes plz , go ahead.

**Comment by GuningShen** [comment]
> > > u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii
> > 
> > 
> > > > u have deleted the `libs` folder and moved the validation lib into the src folder, can u plz explain the motivation behind this change @Shpendiiiii
> > > 
> > > 
> > > I found that structure cumbersome, and used a standard one instead. Additionally, the prisma folder was inside of that and inside the root, which is redundant.
> > > Also, there is no need to have a separate folder inside of a folder for DTOs as well. They can very well live within the folder of the services itself, or within /src itself.
> > > At the end of the day, it is more readable, and most importantly, it runs.
> > 
> > 
> > I agree that the DTO folder can be seen as redundant, but since we are following a monorepo pattern, we have added it to adjust our TypeScript configurations. In the future, there might be genuine cases where moving some code under the libs directory could be beneficial.
> > I also noticed that you removed the app folder and moved it into the src folder. This might break the monorepo pattern that we are trying to achieve. Regarding the location of the Prisma folder, I'm not entirely sure where it should be placed.
> > Could you please provide some insight on the best practices for organizing these folders while maintaining the monorepo structure? @Shpendiiiii
> 
> In that case, I will have to put that part that I worked into its own structure, and allow for other applications to exist. Should I go ahead?
> 
> I didn't realize that there needed to be more apps inside this project, I thought the like system would be the only one.

Sorry for the confusion. We didn't mention this when I add this issue. There is a monorepo structure on the right side of the picture I sent you via slack. Right now we plan to put core code into the core folder and organize shared library objects into a separate folder.

**Pull request closed without merging**
